export enum Command {
  Next = 1,
  Previous,
  SetTrack,
  IncreaseVolume,
  DecreaseVolume,
  SetVolume,
  SetEQ,
  SetMode,
  SetSource,
  Standby,
  Resume,
  Reset,
  Play,
  Pause,
  SetFolder,
  SetGain,
  RepeatPlay,
  Init = 0x3f,
  QueryStatus = 66,
  QueryVolume,
  QueryEQ,
  QueryMode,
  QuerySoftwareVersion,
  QueryTotalFilesOnTFCard,
  QueryTotalFilesOnUDisk,
  QueryTotalFilesOnFlash,
  QueryCurrentTrackOnTFCard = 75,
  QueryCurrentTrackOnUDisk,
  QueryCurrentTrackOnFlash,
}
